"""Build the static portfolio. Run from any directory with Python 3."""
from pathlib import Path
from html import escape
from urllib.parse import urlparse

ROOT = Path(__file__).resolve().parents[1]
NAV = [('home', '/', 'Home'), ('about', '/about/', 'About'), ('work', '/work/', 'Work'), ('directory', '/directory/', 'Directory'), ('socials', '/socials/', 'Socials')]

def card(kicker, title, description, url, image='', tags='', external=False):
    picture = f'<div class="card-art"><img src="{image}" alt="" loading="lazy"></div>' if image else ''
    return f'<a class="project-card {"with-art" if image else ""}" href="{url}" {"target=\"_blank\" rel=\"noopener noreferrer\"" if external else ""}><div class="card-top"><span class="eyebrow">{kicker}</span><span class="arrow" aria-hidden="true">↗</span></div>{picture}<h3>{title}</h3><p>{description}</p>{f"<span class=\"card-tag\">{tags}</span>" if tags else ""}</a>'

def intro(kicker, title, copy):
    return f'<section class="page-intro"><p class="eyebrow">{kicker}</p><h1>{title}</h1><p class="intro-copy">{copy}</p></section>'

emoji = card('01 / STICKER COLLECTION', 'A little Sebi.<br>Every mood.', 'Transparent stickers to search, save, and send. A whole collection of tiny expressions.', 'https://sebidc.github.io/sebi.emojis/', '/assets/images/sebi-frog.png', 'Explore the emoji gallery', True)
faith = card('02 / ACADEMIC PROJECT', 'e-Faith Journey', 'A web project for theology and computer programming.', 'https://sebidc.github.io/efaith-journey/', tags='Visit the website', external=True)
a7 = card('03 / ACADEMIC PROJECT', 'ACAD · A7', 'An image gallery made for academic purposes.', 'https://sebidc.github.io/a7-image-gallery/', tags='Visit the gallery', external=True)

home = '''<section class="hero"><div class="hero-copy"><p class="eyebrow"><span class="dot"></span> MULTIMEDIA EDITOR & CREATOR</p><h1>A little of<br>everything<span class="green">.</span></h1><p class="hero-description">Hi, I’m Sebi dela Cruz. I edit, design, and build — turning ideas into things you can watch, explore, and enjoy.</p><div class="actions"><a class="button primary" href="/work/">Explore my work <span>↗</span></a><a class="button secondary" href="/about/">Get to know me</a></div><div class="hero-footnote"><span>Video</span><span>Design</span><span>Code</span><span>A bit of personality</span></div></div><div class="hero-art"><div class="orbit orbit-one"></div><div class="orbit orbit-two"></div><span class="art-star star-one">✳</span><span class="art-star star-two">✦</span><div class="art-label label-top">always creating</div><div class="art-label label-bottom">a little Sebi in everything</div><img class="hero-sticker" src="/assets/images/sebi-camera.png" alt="Illustrated Sebi holding a camera"><span class="floating-tag tag-video">▶ video & visuals</span><span class="floating-tag tag-code">&lt;/&gt; curious by default</span></div></section>
<section id="me" class="intro-strip"><span class="section-number">01 / HELLO</span><p>From the first cut to the finishing touch.<br><span class="muted">Creative work, with care in the details.</span></p><a class="text-link" href="/about/">More about me ↗</a></section>
<section id="works"><div class="section-heading"><div><p class="eyebrow">02 / THINGS I MAKE</p><h2>Different tools.<br>Same curiosity.</h2></div><p>Editing, visual design, and a growing collection of small web and terminal projects.</p></div><div class="practice-grid"><a class="practice-card" href="/work/"><span class="practice-icon">▶</span><h3>Video & visuals</h3><p>Editing, graphics, and stories made to be seen.</p><span class="text-link">See the work ↗</span></a><a class="practice-card" href="/work/"><span class="practice-icon">✳</span><h3>Design & illustration</h3><p>Playful details, original artwork, and a personal point of view.</p><span class="text-link">Explore projects ↗</span></a><a class="practice-card" href="/work/#tools"><span class="practice-icon">&lt;/&gt;</span><h3>Code & experiments</h3><p>Small tools and sites that make room for new ideas.</p><span class="text-link">Explore projects ↗</span></a></div></section>
<section><div class="section-heading"><div><p class="eyebrow">03 / THE DIRECTORY</p><h2>A few corners<br>of my internet.</h2></div><a class="button secondary" href="/directory/">All destinations ↗</a></div><div class="project-grid home-projects">''' + emoji + faith + a7 + '''</div></section>
<section id="socials" class="contact-banner"><div><p class="eyebrow">04 / SAY HELLO</p><h2>Have something<br>in mind?</h2><p>Explore my social platforms and public links.</p></div><a class="button primary" href="/socials/">Find me online ↗</a><span class="banner-star" aria-hidden="true">✳</span></section>'''

about = intro('01 / ABOUT ME', 'Me, myself,<br>& a few ideas<span class="green">.</span>', 'A creator who enjoys the space between video, design, and code.') + '''<section class="about-layout"><div class="portrait-card"><img src="/assets/images/sebi-wave.png" alt="Sebi emoji smiling and waving hello"><span>sebi dela cruz / multimedia editor</span></div><div class="about-copy"><h2>Hi, I’m Sebi.</h2><p>I’m a multimedia editor with 10 years of experience and hands-on technical expertise ranging from simple video slideshows to CGI production.</p><p>My toolkit spans CapCut, Swift, Blender, and Adobe and Apple creative applications. I enjoy finding the right mix of tools for each idea, then working through the details that bring it together.</p><p>This is my little home on the web: a place for creative work, useful experiments, and personal projects.</p><a class="button secondary" href="/work/">See what I’m making ↗</a></div></section><section class="skills-section"><div class="section-heading"><div><p class="eyebrow">THE TOOLKIT</p><h2>Tools for<br>different ideas.</h2></div><p>Creative applications and code, working together.</p></div><div class="skill-tags"><span>Video editing</span><span>Multimedia design</span><span>CGI</span><span>CapCut</span><span>Blender</span><span>Swift</span><span>Adobe creative apps</span><span>Apple creative apps</span></div></section><section class="note-panel"><div><p class="eyebrow">A SIMPLE PROFILE</p><h3>Prefer a printable version?</h3><p>Save this page as a PDF or print it for a clean, text-focused profile.</p></div><button class="button secondary" type="button" data-print>Print profile ↗</button></section>'''

tools = [
 ('check-installs-tui', 'A terminal interface for browsing packages installed through common macOS package managers.', 'macOS · Terminal'),
 ('ytd-tui', 'A terminal interface for yt-dlp: search, play, and download from one place.', 'Terminal · Media'),
 ('obsidian-dashboard-setup', 'An Obsidian dashboard setup with Dataview, Homepage, Style Settings, and AnuPpuccin-ready configuration.', 'Obsidian · Workspace'),
 ('appldl', 'A macOS command-line tool for finding music through Apple’s public catalog or a local Music.app playlist, with spotdl downloads.', 'macOS · Music'),
]
work = intro('02 / SELECTED WORK', 'Made with<br>curiosity<span class="green">.</span>', 'A collection of public projects and small tools. Always room for one more idea.') + '<section><div class="section-heading"><div><p class="eyebrow">ON THE WEB</p><h2>Small worlds<br>to explore.</h2></div><a class="text-link" href="/directory/">Open the directory ↗</a></div><div class="project-grid">'+emoji+faith+a7+'</div></section><section id="tools"><div class="section-heading"><div><p class="eyebrow">PUBLIC CODE PROJECTS</p><h2>Useful little<br>experiments.</h2></div><p>Browse the source, read the documentation, and follow each project on GitHub.</p></div><div class="tool-grid">'
for name,copy,tags in tools:
    work += card('OPEN SOURCE',name,copy,f'https://github.com/sebidc/{name}',tags=tags,external=True)
work += '</div></section>'

directory = intro('03 / DIRECTORY', 'A place for<br>every project<span class="green">.</span>', 'The map to my little corners of the internet. Choose a destination and make yourself at home.') + '''<section class="directory-section"><div class="directory-toolbar"><div class="filter-group" aria-label="Filter destinations"><button class="filter active" data-filter="all" aria-pressed="true">All</button><button class="filter" data-filter="sites" aria-pressed="false">Project sites</button><button class="filter" data-filter="pages" aria-pressed="false">This website</button><button class="filter" data-filter="code" aria-pressed="false">Code</button></div><label class="search-box"><span aria-hidden="true">⌕</span><input id="directory-search" type="search" placeholder="Find a destination…" aria-label="Search destinations"></label></div><p class="result-count" aria-live="polite"></p><div class="directory-grid">'''
items = [ ('sites','sebi.emojis','Transparent stickers, searchable gallery, and PNG downloads.','https://sebidc.github.io/sebi.emojis/','/sebi.emojis/'), ('sites','e-Faith Journey','A theology and computer programming project.','https://sebidc.github.io/efaith-journey/','/efaith-journey/'), ('sites','ACAD · A7','An image gallery for academic work.','https://sebidc.github.io/a7-image-gallery/','/a7-image-gallery/'), ('pages','About Sebi','A little background, creative skills, and tools.','/about/','/about/'), ('pages','Selected work','Web projects and public code.','/work/','/work/'), ('pages','Social media','All the platforms and public links to connect.','/socials/','/socials/'), ('code','GitHub','All my public repositories, in one place.','https://github.com/sebidc','github.com/sebidc')]
for category,title,copy,url,path in items:
    directory += f'<a class="destination" data-category="{category}" href="{url}" {"target=\"_blank\" rel=\"noopener noreferrer\"" if category != "pages" else ""}><div class="card-top"><span class="eyebrow">{ {"sites":"PROJECT SITE","pages":"THIS WEBSITE","code":"CODE & EXPERIMENTS"}[category]}</span><span class="arrow" aria-hidden="true">↗</span></div><h3>{title}</h3><p>{copy}</p><span class="route">{path}</span></a>'
directory += '</div><p class="empty-state" hidden>No destinations found. Try a different search or filter.</p></section><aside class="note-panel"><div><p class="eyebrow">ROOM TO GROW</p><h3>More ideas, more destinations.</h3><p>New public projects will have a home here as they take shape.</p></div><span class="note-star" aria-hidden="true">✳</span></aside>'

def social_links():
    cards=[]
    for line in (ROOT/'content/socials.md').read_text().splitlines():
        if not line.startswith('|'): continue
        columns=[part.strip() for part in line.strip('|').split('|')]
        if len(columns)!=2: continue
        label,url=columns
        if label == 'Platform' or label.startswith('---'): continue
        parsed=urlparse(url)
        available=(parsed.scheme=='https' and bool(parsed.netloc)) or (parsed.scheme=='mailto' and '@' in parsed.path)
        if available:
            cards.append(f'<a class="social-card" data-name="{escape(label, quote=True)}" data-available="true" href="{escape(url, quote=True)}" {"target=\"_blank\" rel=\"noopener noreferrer\"" if parsed.scheme == "https" else ""}><span class="social-symbol" aria-hidden="true">↗</span><h3>{escape(label)}</h3><span class="social-status">{ "Send an email" if parsed.scheme == "mailto" else "Visit profile" }</span></a>')
        else:
            cards.append(f'<div class="social-card placeholder" data-name="{escape(label, quote=True)}" data-available="false"><span class="social-symbol" aria-hidden="true">+</span><h3>{escape(label)}</h3><span class="social-status">Link coming soon</span></div>')
    return ''.join(cards)
socials = intro('04 / SOCIALS', 'Let’s stay<br>connected<span class="green">.</span>', 'All the places to connect, follow, and explore. Links are added here as each profile is ready.') + '<section class="socials-section"><div class="directory-toolbar"><div class="filter-group" aria-label="Filter social profiles"><button class="filter active" data-social-filter="all" aria-pressed="true">All platforms</button><button class="filter" data-social-filter="available" aria-pressed="false">Available links</button></div><label class="search-box"><span aria-hidden="true">⌕</span><input id="social-search" type="search" placeholder="Find a platform…" aria-label="Search social platforms"></label></div><p class="social-count result-count" aria-live="polite"></p><div class="social-grid">'+social_links()+'</div><p class="social-empty empty-state" hidden>No platforms found. Try a different search or filter.</p></section>'

pages={'home':('Sebi dela Cruz — Multimedia Editor & Creator',home,'Video, design, code, and a little personality. Explore Sebi dela Cruz’s creative work and public projects.'),'about':('About — Sebi dela Cruz',about,'Meet Sebi dela Cruz, a multimedia editor working across video, visual design, CGI, and code.'),'work':('Work — Sebi dela Cruz',work,'Explore Sebi’s public websites and terminal tools.'),'directory':('Directory — Sebi dela Cruz',directory,'Find Sebi’s project sites, emoji gallery, portfolio pages, and public code.'),'socials':('Socials — Sebi dela Cruz',socials,'Find Sebi’s social profiles and a directory of platforms to connect on.')}
for key,(title,body,description) in pages.items():
    route='/' if key=='home' else f'/{key}/'
    nav=''.join(f'<a href="{url}" {"aria-current=\"page\"" if key==slug else ""}>{label}</a>' for slug,url,label in NAV)
    html=f'''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="theme-color" content="#333c43"><meta name="description" content="{escape(description)}"><title>{escape(title)}</title><link rel="canonical" href="https://sebidc.github.io{route}"><meta property="og:title" content="{escape(title)}"><meta property="og:description" content="{escape(description)}"><meta property="og:type" content="website"><meta property="og:url" content="https://sebidc.github.io{route}"><meta property="og:image" content="https://sebidc.github.io/assets/images/sebi-camera.png"><link rel="icon" type="image/svg+xml" href="/assets/favicon.svg"><link rel="preload" href="/assets/fonts/agrandir-grand-heavy.woff2" as="font" type="font/woff2" crossorigin><link rel="stylesheet" href="/assets/style.css"><script src="/assets/site.js" defer></script></head><body class="page-{key}"><a class="skip-link" href="#main">Skip to content</a><div class="site-shell"><header class="site-header"><a class="wordmark" href="/" aria-label="Sebi home">sebi<span class="green">.dc</span><span class="wordmark-star" aria-hidden="true">✳</span></a><nav aria-label="Main navigation">{nav}</nav></header><main id="main">{body}</main><footer><a class="wordmark" href="/">sebi<span class="green">.dc</span></a><p>A little creativity. A lot of curiosity.</p><div><a href="/directory/">Directory ↗</a><a href="https://github.com/sebidc" target="_blank" rel="noopener noreferrer">GitHub ↗</a><a href="/socials/">Socials ↗</a></div></footer></div></body></html>'''
    path=ROOT/'index.html' if key=='home' else ROOT/key/'index.html'
    path.parent.mkdir(exist_ok=True)
    path.write_text(html)
# Keep the error page useful without requiring JavaScript.
(ROOT/'404.html').write_text('''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Page not found — Sebi</title><link rel="stylesheet" href="/assets/style.css"></head><body><main class="site-shell page-intro"><p class="eyebrow">404 / LOST IN THE DIRECTORY</p><h1>A little<br>detour.</h1><p class="intro-copy">That page isn’t here. Let’s find the right place.</p><div class="actions"><a class="button primary" href="/">Back home ↗</a><a class="button secondary" href="/directory/">Open directory ↗</a></div></main></body></html>''')
print('Built Home, About, Work, Directory, Socials, and 404 pages.')

(ROOT/'contact').mkdir(exist_ok=True)
(ROOT/'contact/index.html').write_text('<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta http-equiv="refresh" content="0; url=/socials/"><link rel="canonical" href="https://sebidc.github.io/socials/"><title>Socials — Sebi dela Cruz</title><link rel="stylesheet" href="/assets/style.css"></head><body><main class="site-shell page-intro"><h1>Find me online.</h1><a class="button primary" href="/socials/">Open Socials ↗</a></main></body></html>')
